// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: country.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from country.proto</summary>
public static partial class CountryReflection {

  #region Descriptor
  /// <summary>File descriptor for country.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static CountryReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg1jb3VudHJ5LnByb3RvKnkKB0NvdW50cnkSEgoOVW5rbm93bkNvdW50cnkQ",
          "ABIHCgNNWVMQARIHCgNHQlIQAhIHCgNVS1IQAxIHCgNVQUUQBBIHCgNOWkwQ",
          "BRIHCgNFU1AQBhIHCgNIS0cQBxIHCgNJUkwQCBIJCgVBVVZJQxAJEgcKA0xU",
          "VRAKKh8KCExhbmd1YWdlEhMKD1Vua25vd25MYW5ndWFnZRAAYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Country), typeof(global::Language), }, null));
  }
  #endregion

}
#region Enums
public enum Country {
  [pbr::OriginalName("UnknownCountry")] UnknownCountry = 0,
  [pbr::OriginalName("MYS")] Mys = 1,
  [pbr::OriginalName("GBR")] Gbr = 2,
  [pbr::OriginalName("UKR")] Ukr = 3,
  [pbr::OriginalName("UAE")] Uae = 4,
  [pbr::OriginalName("NZL")] Nzl = 5,
  [pbr::OriginalName("ESP")] Esp = 6,
  [pbr::OriginalName("HKG")] Hkg = 7,
  [pbr::OriginalName("IRL")] Irl = 8,
  [pbr::OriginalName("AUVIC")] Auvic = 9,
  [pbr::OriginalName("LTU")] Ltu = 10,
}

public enum Language {
  [pbr::OriginalName("UnknownLanguage")] UnknownLanguage = 0,
}

#endregion


#endregion Designer generated code
